image: node:20-alpine

stages:
  - build
  - deploy

# before_script:
  # - cd CalendarProject-main

build_app:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 30mins

deploy_to_github:
  stage: deploy
  only:
    - main
  script:
    - npm install
    - npm run build
    - npx gh-pages -d dist --report https://x-access-token:$GITHUB_TOKEN@github.com/Cozmin-Ghenea/Calendar_Project_FirstBatch.git -m "Deploy from Gitlab CI [skip ci]""